/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package averageage;

import averageage.service.AverageAgeService;

import java.util.Arrays;

public class AverageAgeApp {

    private static final AverageAgeService averageAgeService = new AverageAgeService();

    public static void main(String[] args) {
        if (args.length != 2 ||
            args[0] == null ||
            args[1] == null ||
            args[0].length() < 1 ||
            args[1].length() < 1) {
            throw new Error("Invalid arguments.");
        }

        System.out.println(averageAgeService.average(
            args[0].split("\\s+"),
            Arrays.stream(
                args[1].split("\\s+")
            ).mapToInt(Integer::parseInt).toArray()
        ));
    }
}
